name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:humble-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install LTTng
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository ppa:lttng/stable-2.13
          sudo apt-get update
          sudo apt-get install -y python3-babeltrace python3-lttng python3-bt2
        shell: bash

      - name: ROSDEP install
        run: |
          sudo apt-get install -y python3-rosdep
          # sudo rosdep init
          rosdep update
          rosdep install -i --from-paths . -y --rosdistro humble

      - name: Install dependent packages
        run: python3 -m pip install -r src/requirements.txt

      - name: Get package list
        run: |
          dpkg -l > package_list.txt
          python3 -m pip list > pip_list.txt

      - name: Upload package list
        uses: actions/upload-artifact@v3
        with:
          name: package_list
          path: |
            package_list.txt
            pip_list.txt

      - name: Clone caret_analyze_cpp_imple
        run: |
          git clone https://github.com/tier4/caret_analyze_cpp_impl.git
          cd caret_analyze_cpp_impl/
          mv CARET_analyze_cpp_impl src

      - name: Restore Cache
        id: cppimpl-cache
        uses: actions/cache/restore@v3
        with:
          path: caret_analyze_cpp_impl/install
          key: ${{ runner.os }}-node-cppimple-${{ hashFiles('caret_analyze_cpp_impl/src/**') }}

      - name: Build caret_analyze_cpp_imple
        if: steps.cppimpl-cache.outputs.cache-hit != 'true'
        run: |
          source /opt/ros/humble/setup.bash
          cd caret_analyze_cpp_impl/
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Cache caret_analyze_cpp_imple
        if: steps.cppimpl-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: caret_analyze_cpp_impl/install
          key: ${{ runner.os }}-node-cppimple-${{ hashFiles('caret_analyze_cpp_impl/src/**') }}

      - name: Run pytest
        run: |
          mv caret_analyze_cpp_impl/install /__w
          export PYTHONPATH=/__w/install/caret_analyze_cpp_impl/lib/python3.10/site-packages:$PYTHONPATH
          . /opt/ros/humble/setup.sh
          python3 -m pytest
